apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.port | int }}
              name: http
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TELOXIDE_TOKEN
              value: {{ .Values.telegram.botToken | quote }}
            - name: PORT
              value: {{ .Values.port | quote }}
            - name: RUST_LOG
              value: {{ .Values.logLevel | quote }}
            - name:  WEBHOOK_TOKEN
              value: {{ .Values.telegram.webHookToken | quote }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
      imagePullSecrets:
        - name: acteek
