replicas: 2
logLevel: info
port: 8080

telegram:
  botToken: "my_awesome_token"
  webHookToken: sGRStaqTe163yJ6PhYiKQitzogSMFg4WC

image:
  name: registry.digitalocean.com/acteek/dice-bot
  tag: main-7e7ec826
hpa:
  min: 1
  max: 3
resources:
  limits:
    cpu: '0.1'
    memory: 64Mi
  requests:
    cpu: '0.1'
    memory: 64Mi
