replicas: 1
logLevel: info
port: 8080

telegram:
  botToken: "my_awesome_token"
  webHookToken: 75ad4342-0ed6-4be8-aff9-89361f7da53d

image:
  name: registry.digitalocean.com/acteek/dice-bot
  tag: main-7e7ec826

resources:
  limits:
    cpu: '0.1'
    memory: 64Mi
  requests:
    cpu: '0.1'
    memory: 64Mi
