name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@main
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Set outputs
        id: vars
        run: echo "image_tag=$GITHUB_REF_NAME.$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Docker image build
        run: |
          docker build -t registry.digitalocean.com/acteek/dice-bot:${{ steps.vars.outputs.image_tag }} $GITHUB_WORKSPACE/.
          docker push registry.digitalocean.com/acteek/dice-bot:${{ steps.vars.outputs.image_tag }}
